name: Build

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    env:
      QT_VERSION: 6.7.3
      QMAKE: ${{ github.workspace }}/${{ env.QT_VERSION }}/gcc_64/bin/qmake
    steps:
      - uses: actions/checkout@v6

      - name: Install apt packages
        run: |
          sudo apt update -y
          sudo apt install -y \
            build-essential \
            cmake \
            curl \
            libgl1-mesa-dev \
            python3 \
            python3-pip

      - name: Install aqtinstall
        run: |
          python3 -m pip install aqtinstall

      - name: Install Qt
        run: |
          aqt install-qt linux desktop $QT_VERSION linux_gcc_64

      - name: Build clide
        run: |
          cargo b --release

      - name: Test libclide
        run: |
          cargo test -p libclide

      - name: Test clide
        run: |
          cargo test
